name: Run Angular Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # Angular fonctionne bien avec Node 16 ou 18

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Lancer les tests Angular
      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
